trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '=2.6.2'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    bundle exec ruby ./update.rb
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    AZURE_PROJECT_PATH: YOUR_ORG/YOUR_PROJECT/_git/YOUR_REPO
    AZURE_WORK_ITEM: WORK_ITEM_ID
  displayName: 'Update dependencies'